force-app/main/default/objects/QuizQuestion__c/QuizQuestion__c.object-meta.xml
<CustomObject>
    <label>QuizQuestion</label>
    <nameField>
        <displayFormat>Que-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizQuestion__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option_A</fullName>
            </value>
            <value>
                <fullName>Option_B</fullName>
            </value>
            <value>
                <fullName>Option_C</fullName>
            </value>
            <value>
                <fullName>Option_D</fullName>
            </value>
            <value>
                <fullName>Option_E</fullName>
            </value>
            <value>
                <fullName>Option_F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/QuizTestName__c.field-meta.xml
<CustomField>
    <fullName>QuizTestName__c</fullName>
    <label>QuizTest</label>
    <referenceTo>QuizTest__c</referenceTo>
    <relationshipLabel>QuizQuestions</relationshipLabel>
    <relationshipName>QuizQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizTest__c/QuizTest__c.object-meta.xml
<CustomObject>
    <label>QuizTest</label>
    <nameField>
        <displayFormat>quiz-{0000}</displayFormat>
        <label>Quiz Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizTest__c/fields/Time_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_in_minutes__c</fullName>
    <label>Time in minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/QuizUserTest__c.object-meta.xml
<CustomObject>
    <label>QuizUserTest</label>
    <nameField>
        <displayFormat>uTest-{0000}</displayFormat>
        <label>uTest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizUserTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizUserTest__c/fields/QuizQuestion__c.field-meta.xml
<CustomField>
    <fullName>QuizQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuizQuestion</label>
    <referenceTo>QuizQuestion__c</referenceTo>
    <relationshipName>quizUserTests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/fields/Selected_Options__c.field-meta.xml
<CustomField>
    <fullName>Selected_Options__c</fullName>
    <label>Selected Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option_A</fullName>
            </value>
            <value>
                <fullName>Option_B</fullName>
            </value>
            <value>
                <fullName>Option_C</fullName>
            </value>
            <value>
                <fullName>Option_D</fullName>
            </value>
            <value>
                <fullName>Option_E</fullName>
            </value>
            <value>
                <fullName>Option_F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/fields/Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Date__c</fullName>
    <label>Test Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Test Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/fields/Test_Time__c.field-meta.xml
<CustomField>
    <fullName>Test_Time__c</fullName>
    <label>Test Time</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuizUsersTestController.cls
public with sharing class QuizUsersTestController {
    @AuraEnabled
    public static void saveQuizUsersTestData(Map<Id, String> data, 
        String testName, String testDate, String testTime, String timeTaken ){
        try {
            // QuizQuestion__c, Selected_Options__c, Test_Name__c, 
            //Test_Date__c, Test_Time__c FROM quizUserTest__c
            List<quizUserTest__c> quizTestList = new List<quizUserTest__c>();
            for(Id quizquestionId : data.keySet())
            {
                quizUserTest__c quiz = new quizUserTest__c();
                quiz.QuizQuestion__c = quizquestionId;
                quiz.Selected_Options__c = data.get(quizquestionId);
                quiz.Test_Name__c = testName;
                quiz.Test_Date__c = testDate;
                quiz.Test_Time__c = testTime;
                quiz.Time_Taken__c = timeTaken;
                quizTestList.add(quiz);
            }
            insert quizTestList;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<QuizUserTest__c> getQuizUserTestData(String testName, 
        String testDate, String testTime){
        try {
            return [SELECT Id, Selected_Options__c, Test_Name__c, Test_Date__c,
                Test_Time__c, Result__c, QuizQuestion__r.Question__c, 
                QuizQuestion__r.Answer__c, Time_Taken__c,
                QuizQuestion__r.Type__c, Owner.Name, QuizQuestion__r.QuizTestName__r.Time_in_minutes__c
                FROM QuizUserTest__c WHERE Test_Name__c =:testName 
                AND Test_Date__c =:testDate 
                AND Test_Time__c =:testTime];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<QuizUserTest__c> getQuizUsersTestDataDirect(){
        try {
            return [SELECT Id, Test_Name__c, Test_Date__c,
                Test_Time__c
                FROM QuizUserTest__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}