force-app/main/default/objects/QuizQuestion__c/QuizQuestion__c.object-meta.xml
<CustomObject>
    <label>QuizQuestion</label>
    <nameField>
        <displayFormat>Que-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizQuestion__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option_A</fullName>
            </value>
            <value>
                <fullName>Option_B</fullName>
            </value>
            <value>
                <fullName>Option_C</fullName>
            </value>
            <value>
                <fullName>Option_D</fullName>
            </value>
            <value>
                <fullName>Option_E</fullName>
            </value>
            <value>
                <fullName>Option_F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_A__c.field-meta.xml
<CustomField>
    <fullName>Option_A__c</fullName>
    <label>Option_A</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_B__c.field-meta.xml
<CustomField>
    <fullName>Option_B__c</fullName>
    <label>Option_B</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_C__c.field-meta.xml
<CustomField>
    <fullName>Option_C__c</fullName>
    <label>Option_C</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_D__c.field-meta.xml
<CustomField>
    <fullName>Option_D__c</fullName>
    <label>Option_D</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_E__c.field-meta.xml
<CustomField>
    <fullName>Option_E__c</fullName>
    <label>Option_E</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Option_F__c.field-meta.xml
<CustomField>
    <fullName>Option_F__c</fullName>
    <label>Option_F</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/QuizTestName__c.field-meta.xml
<CustomField>
    <fullName>QuizTestName__c</fullName>
    <label>QuizTest</label>
    <referenceTo>QuizTest__c</referenceTo>
    <relationshipLabel>QuizQuestions</relationshipLabel>
    <relationshipName>QuizQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuizQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizTest__c/QuizTest__c.object-meta.xml
<CustomObject>
    <label>QuizTest</label>
    <nameField>
        <displayFormat>quiz-{0000}</displayFormat>
        <label>Quiz Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizTest__c/fields/Quiz_Name__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Name__c</fullName>
    <label>Quiz Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QuizTest__c/fields/Time_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_in_minutes__c</fullName>
    <label>Time in minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuizQuestionController.cls
public with sharing class QuizQuestionController {
    @AuraEnabled
    public static void saveQuizQuestion(String question, String description, Map<String, String> options, 
        String answer, String type, Id testId){
        try {
            //SELECT Id, Question__c, Option_A__c, Option_B__c, Option_C__c, 
            //Option_D__c, Answer__c, Type__c, QuizTestName__c FROM QuizQuestion__c
            QuizQuestion__c quizQuestionObj = new QuizQuestion__c();
            quizQuestionObj.Question__c = question;
            quizQuestionObj.Description__c = description;
            for(String optionName : options.keySet())
            {
                switch on optionName {
                    when 'Option_A' {
                        quizQuestionObj.Option_A__c = options.get(optionName);
                    }
                    when 'Option_B' {
                        quizQuestionObj.Option_B__c = options.get(optionName);
                    }
                    when 'Option_C' {
                        quizQuestionObj.Option_C__c = options.get(optionName);
                    }
                    when 'Option_D' {
                        quizQuestionObj.Option_D__c = options.get(optionName);
                    }
                    when 'Option_E' {
                        quizQuestionObj.Option_E__c = options.get(optionName);
                    }
                    when 'Option_F' {
                        quizQuestionObj.Option_F__c = options.get(optionName);
                    }
                    when else {
                        //
                    }
                }
            }
            quizQuestionObj.Answer__c = answer;
            quizQuestionObj.Type__c = type;
            quizQuestionObj.QuizTestName__c = testId;

            insert quizQuestionObj;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<QuizQuestion__c> getQuizQuestions(String testName){
        try {
            return [SELECT Id, Question__c, Option_A__c, Option_B__c, Option_C__c, 
                        Option_D__c, Option_E__c, Option_F__c, Answer__c, Type__c, Description__c, QuizTestName__r.Quiz_Name__c ,
                            QuizTestName__r.Time_in_minutes__c
                            FROM QuizQuestion__c WHERE QuizTestName__r.Quiz_Name__c =:testName];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}