force-app/main/default/objects/QuizQuestion__c/QuizQuestion__c.object-meta.xml
<CustomObject>
    <label>QuizQuestion</label>
    <nameField>
        <displayFormat>Que-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizQuestion__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option_A</fullName>
            </value>
            <value>
                <fullName>Option_B</fullName>
            </value>
            <value>
                <fullName>Option_C</fullName>
            </value>
            <value>
                <fullName>Option_D</fullName>
            </value>
            <value>
                <fullName>Option_E</fullName>
            </value>
            <value>
                <fullName>Option_F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/QuizUserTest__c.object-meta.xml
<CustomObject>
    <label>QuizUserTest</label>
    <nameField>
        <displayFormat>uTest-{0000}</displayFormat>
        <label>uTest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuizUserTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuizUserTest__c/fields/QuizQuestion__c.field-meta.xml
<CustomField>
    <fullName>QuizQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuizQuestion</label>
    <referenceTo>QuizQuestion__c</referenceTo>
    <relationshipName>quizUserTests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuizUserTest__c/fields/Selected_Options__c.field-meta.xml
<CustomField>
    <fullName>Selected_Options__c</fullName>
    <label>Selected Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option_A</fullName>
            </value>
            <value>
                <fullName>Option_B</fullName>
            </value>
            <value>
                <fullName>Option_C</fullName>
            </value>
            <value>
                <fullName>Option_D</fullName>
            </value>
            <value>
                <fullName>Option_E</fullName>
            </value>
            <value>
                <fullName>Option_F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuizUserTestService.cls
public with sharing class QuizUserTestService {
    public static void setQuizResult(List<QuizUserTest__c> quizList)
    {
        Map<Id, String> questionsList = new Map<Id, String>();
        List<Id> questionIdList = new List<Id>();
        for(QuizUserTest__c quiz : quizList)
        {
            questionIdList.add(quiz.QuizQuestion__c);
        }

        for(QuizQuestion__c question : [SELECT Id, Answer__c FROM QuizQuestion__c WHERE Id IN :questionIdList])
        {
            questionsList.put(question.Id, question.Answer__c);
        }

        for(QuizUserTest__c quiz : quizList)
        {
            if(questionsList.containsKey(quiz.QuizQuestion__c))
            {
                if(questionsList.get(quiz.QuizQuestion__c) == quiz.Selected_Options__c)
                {
                    quiz.Result__c = '100';
                }
                else {
                    quiz.Result__c = '0';
                }
            }
        }
    }
}